export const genMuminPrograms = [
  {
    id: "arabic-tajweed",
    tab: "Arabic–Tajweed",
    title: "Arabic & Tajweed",
    subtitle: "Understand and Recite the Quran",
    arabic: "العربية والتجويد",
    description: "Build Arabic reading, speaking, and Quranic vocabulary alongside correct pronunciation and Tajweed. Guided practice helps children connect understanding with confident, beautiful recitation.",
    points: ["Arabic Reading & Speaking", "Quranic Vocabulary & Grammar", "Makharij & Tajweed Rules", "Guided Recitation Practice"],
    stats: [{ value: "Arabic", label: "Understanding" }, { value: "Tajweed", label: "Recitation" }, { value: "Practice", label: "Confidence" }],
    leadsTo: "Seerah",
    accent: "#9bd3db",
  },
  {
    id: "seerah",
    tab: "Seerah",
    title: "The Prophet's Seerah",
    subtitle: "Stories, Identity & Prophetic Character",
    arabic: "السيرة النبوية",
    description: "Discover the life of Prophet Muhammad (peace be upon him) through stories, reflection, and practical lessons. Help children build love for the Prophet and bring his example into everyday choices.",
    points: ["Life of the Prophet", "Prophetic Values & Identity", "Reflection & Discussion", "Everyday Character Building"],
    stats: [{ value: "Stories", label: "Learning" }, { value: "Values", label: "Character" }, { value: "Faith", label: "Identity" }],
    leadsTo: "Life Skills & Leadership",
    accent: "#c3b4f4",
  },
  {
    id: "leadership",
    tab: "Life Skills & Leadership",
    title: "Life Skills & Leadership",
    subtitle: "Confident, Responsible Young Muslims",
    arabic: "مهارات الحياة والقيادة",
    description: "Develop communication, emotional awareness, problem-solving, and leadership grounded in Islamic values. Children practise teamwork, take responsibility, and turn learning into purposeful action.",
    points: ["Communication & Confidence", "Emotional Awareness & Resilience", "Problem-Solving & Life Skills", "Teamwork & Responsible Leadership"],
    stats: [{ value: "Skills", label: "Everyday Life" }, { value: "Purpose", label: "Leadership" }, { value: "Action", label: "Responsibility" }],
    leadsTo: "Community Building",
    accent: "#a5c5f4",
  },
  {
    id: "community",
    tab: "Community Building",
    title: "Community Building",
    subtitle: "Qabail, House Points & Shared Achievement",
    arabic: "بناء المجتمع",
    description: "Grow together through the Qabail house system, where children build belonging, support their teammates, and contribute to shared goals. House points and rewards encourage participation, positive character, and community spirit.",
    points: ["Qabail Houses & Team Identity", "House Points & Reward System", "Team Challenges & Collaboration", "Service, Adab & Shared Responsibility"],
    stats: [{ value: "Qabail", label: "Belonging" }, { value: "Points", label: "Participation" }, { value: "Rewards", label: "Recognition" }],
    leadsTo: "Parental Sessions",
    accent: "#97d8b0",
  },
  {
    id: "parents",
    tab: "Parental Sessions",
    title: "Parental Sessions",
    subtitle: "Families Learning and Growing Together",
    arabic: "جلسات الوالدين",
    description: "Support your child's journey through dedicated parental sessions focused on Islamic Tarbiyah, learning at home, and everyday parenting challenges. Connect with the program, share questions, and build consistent guidance between home and learning.",
    points: ["Islamic Tarbiyah & Parenting Guidance", "Supporting Learning at Home", "Questions, Discussion & Shared Support", "Parent–Program Partnership"],
    stats: [{ value: "Parents", label: "Partnership" }, { value: "Support", label: "Home Learning" }, { value: "Growth", label: "Together" }],
    leadsTo: "Continued Family & Community Growth",
    accent: "#f0c18f",
  },
] as const;

export type GenMuminProgramId = (typeof genMuminPrograms)[number]["id"];
